apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-training-app
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: kacpi52/training_app_api:latest
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          value: psql-db-service
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
