version: "3.8"

services:
  diet-postgresql:
    container_name: diet_postgresql
    image: postgres:15.1
    restart: always
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DBNAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"

networks:
  network_diet:
    name: diet_network
    driver: bridge

volumes:
  postgresql_data:
    name: postgres-data-diet-volume
