name: deploy to aws infrastructure 

on:
    push:
        branches:
            - main
            - prod
    pull_request:
      branches:
        - main
        - prod

jobs:
    deploy_tf:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: set variables
            # checking from which branch wf is runned then setting workspace 
              run: |
                if [[ $GITHUB_REF == 'refs/heads/prod' ]]; then
                    echo "prod" > .workspace
                else
                    echo "staging" > .workspace
                fi
            - name: terraform apply
              env:
                AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID}}
                AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                TF_VAR_db_password: ${{secrets.TF_VAR_DB_PASSWORD}}
              run: |
                workspace=$(cat .workspace)
                cd infra/
                docker compose run --rm terraform -chdir=deploy/ init
                docker compose run --rm terraform -chdir=deploy/ workspace select -or-create $workspace
                docker compose run --rm terraform -chdir=deploy/ apply -auto-approve