name: push to ghcr
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push-images:
    uses: kacpi52/common-actions/.github/workflows/docker-build-and-push.yml@main
    with:
      name: Backend
      context: ./server
      file: ./server/Dockerfile
      image-names: kacpi52/training_app_api
      push: true

  push-frontend:
    uses: kacpi52/common-actions/.github/workflows/docker-build-and-push.yml@main
    with:
      name: Frontend
      context: ./frontend
      file: ./frontend/Dockerfile
      image-names: kacpi52/training_app_frontend
      push: true