name: push to ghcr
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push-images:
    uses: kacpi52/common-actions/.github/workflows/docker-build-push.yaml@main
    with:
      name: Backend
      context: ./server
      file: ./server/Dockerfile
      image-names: kacpi52/training_app_api
      push: true
      tag-rules: |
        type=raw,value=${{ github.sha }},priority=100
        type=raw,value=latest,priority=50

  push-frontend:
    uses: kacpi52/common-actions/.github/workflows/docker-build-push.yaml@main
    with:
      name: Frontend
      context: ./frontend
      file: ./frontend/Dockerfile
      image-names: kacpi52/training_app_frontend
      push: true
      tag-rules: |
        type=raw,value=${{ github.sha }},priority=100
        type=raw,value=latest,priority=50