name: SAST validation

on:
  workflow_dispatch:

jobs:
  sast-server:
    name: Validate Go API code
    uses: kacpi52/common-actions/.github/workflows/sast-validation-semgrep.yaml@main
    with:
      rules: "p/go"
      upload-artifact: true
      upload-release-assets: false
      upload-results-github-security: false

  sast-frontend:
    name: Validate Nuxt 3 code
    uses: kacpi52/common-actions/.github/workflows/sast-validation-semgrep.yaml@main
    with:
      rules: "p/javascript"
      upload-artifact: false
      upload-release-assets: false
      upload-results-github-security: false
